# Generated by Django 4.2.5 on 2023-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
