# Generated by Django 4.2.5 on 2023-09-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('faculty', 'Faculty'), ('student', 'Student')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
