# Generated by Django 4.2.5 on 2023-09-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_course_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='name',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
