# Generated by Django 4.2.5 on 2023-09-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_course_name_remove_user_parent_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('faculty', 'Faculty'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
