# Generated by Django 4.2.5 on 2023-09-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(default='6 months', max_length=300)),
                ('offline_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('full_name', models.CharField(default=False, max_length=100)),
                ('cochin_date', models.CharField(blank=True, max_length=50, null=True)),
                ('calicut_date', models.CharField(blank=True, max_length=50, null=True)),
                ('online', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_no', models.CharField(max_length=100)),
                ('mod_heading', models.CharField(max_length=100)),
                ('mod_description', models.CharField(max_length=1000)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course_batch.course')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=100)),
                ('batch_name', models.CharField(default=True, max_length=100)),
                ('startdate', models.CharField(default=True, max_length=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course_batch.course')),
            ],
        ),
    ]
