# Generated by Django 4.2.5 on 2023-09-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_batch', '0003_rename_online_course_online_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offline_active',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='online_active',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='student', max_length=20),
        ),
    ]
